import React from 'react'
export const metadata = {
  title: 'Auth for layout',
  description: 'Generated by Next.js',
}
function page() {
  return (
    <div>
      <h1>About section</h1>
    </div>
  )
}

export default page
